spring.application.name=telemetry-demo

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Compare my entities with the database and create/update tables as needed.
spring.jpa.hibernate.ddl-auto=update
# see the psql
spring.jpa.show-sql=true