name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      terraform_changed: ${{ steps.check-terraform.outputs.changed }}
      spring_changed: ${{ steps.check-spring.outputs.changed }}
      github_learning_changed: ${{steps.check-github-learning.outputs.changed}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Terraform changes
        id: check-terraform
        shell: bash
        run: |
          if git diff --quiet HEAD~1 HEAD -- terraform/ lambda/; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Spring changes
        id: check-spring
        shell: bash
        run: |
          if git diff --quiet HEAD~1 HEAD -- learning/java-spring/; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Github Learning changes
        id: check-github-learning
        shell: bash
        run: |
          if git diff --quiet HEAD~1 HEAD -- learning/github-actions-learning/; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

  terraform:
    needs: detect-changes

    if: needs.detect-changes.outputs.terraform_changed == 'true'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    # uses: ./.github/workflows/terraform.yml

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: arn:aws:iam::941141115076:role/github-actions-terraform
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Build Lambda Package
        working-directory: lambda
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
